#!/usr/bin/python
from db import ItemDailyTable
from sys import argv, exit
import matplotlib.pyplot as plt

if len( argv ) != 3:
	print( "plotter [DB NAME] [ITEM NAME]" )
	exit( 1 )

DB_NAME = argv[ 1 ]
ITEM_NAME = argv[ 2 ]

by_item = ItemDailyTable( DB_NAME )

selection, columns = by_item.select( 
        keys=[ "name", "timestamp", "price" ], 
        where={ "name": '"' + ITEM_NAME + '"' },
        orderby=[ "timestamp" ]
)
time = [ el[ 1 ] for el in selection ]
price = [ el[ 2 ] for el in selection ]

plt.plot( time, price )

plt.xlabel('time (ms)')
plt.ylabel('price')
plt.title( selection[ 0 ][ 0 ] + ' Price Plot' )
plt.grid( True )
plt.savefig( selection[ 0 ][ 0 ] + '.png' )
plt.show()

