#!/bin/sh
#
# rsmodeler cron daily

set -e

# get our python full path
pythonpath=$(which python3)

# get our database filename
date_value=$(date +%Y-%m-%d)

#$pythonpath /home/jack/rsmodeler/driver.py --verbose 1 --day "${date_value}" "/home/jack/rsmodeler/db/rsmodeler.db"
$pythonpath /home/jack/rsmodeler/driver.py --verbose 1 --materials "/home/jack/rsmodeler/db/rsmodeler.db"
