#!/bin/sh
#
# rsmodeler cron daily

set -e

# get our python full path
pythonpath=$(which python3)

# get our database filename
date_value=$(date +%d)

# Check if it's the first day of the month
if [ "$date_value" -eq 04 ]; then
    echo $pythonpath /home/jack/rsmodeler/driver.py --verbose 1 --timer 10 --materials --alch "/home/jack/rsmodeler/db/rsmodeler.db"
    $pythonpath /home/jack/rsmodeler/driver.py --verbose 1 --timer 10 --materials --alch "/home/jack/rsmodeler/db/rsmodeler.db"
else
    echo $pythonpath /home/jack/rsmodeler/driver.py --verbose 1 --timer 10 "/home/jack/rsmodeler/db/rsmodeler.db"
    $pythonpath /home/jack/rsmodeler/driver.py --verbose 1 --timer 10 "/home/jack/rsmodeler/db/rsmodeler.db"
fi
