#!/bin/sh
#
# rsmodeler cron daily

set -e

# get our python full path
pythonpath=$(which python)

# get our database filename
date_value=$(date +%Y-%m-%d)

$pythonpath /home/jack/rsmodeler/driver.py --verbose --day '${date_value}' "/home/jack/rsmodeler/db/rsmodeler.db"
