#!/usr/bin/python
from etl import extract, transform
from sqlite3 import connect
from sys import argv
from manager import TransformManager
from json import dump, load as jload
from multiprocessing import cpu_count

extract( "item.db", members=False )
#transform( "item.db" )
