#!/usr/bin/python
from etl import extract, transform, load
from sqlite3 import connect
from sys import argv
from manager import TransformManager
from json import dump, load as jload

results = extract( alphabet="abcd" )
#f = open( "results.json", "rb" )
#results = jload( f )
results = transform( results )
#print( results )
load( results, "item.db" )
