#!/usr/bin/python

from sqlite3 import connect

db = connect( "item.db" )
cursor = db.cursor()
print_write = ""

while True:
	command = raw_input( "> " )

	if command == "write":
		fp = open( "sqlite.csv", "wb" )
		fp.write( print_write )
		fp.close()
		continue	

	res = None
	try:
		res = cursor.execute( command ).fetchall()
	except Exception as e:
		print( e )
		print( "\n" )
	
	for row in res:
		print( row )
		print_write = print_write + "\n" + ", ".join( [ str( e ) for e in row ] )

	print( "total results: " + str( len( res ) ) )


